on: 
  push:
    branches: [ Momin ]
  

  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.16
    - name: Install dependencies
      run: |
        make install
    - name: lint
      run: |
        make lint
